// <auto-generated />
using System;
using Deckino.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deckino.Api.Migrations
{
    [DbContext(typeof(DeckinoDbContext))]
    [Migration("20261007171922_PriceSnapshots")]
    partial class PriceSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deckino.Api.Accounts.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Binders.Binder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<bool>("IsSelling")
                        .HasColumnType("boolean")
                        .HasColumnName("is_selling");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_binders");

                    b.HasIndex("OwnerId", "UpdatedAt")
                        .HasDatabaseName("ix_binders_owner_id_updated_at");

                    b.ToTable("binders", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Binders.BinderCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BinderId")
                        .HasColumnType("uuid")
                        .HasColumnName("binder_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Finish")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("finish");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("language");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_binder_cards");

                    b.HasIndex("ScryfallId")
                        .HasDatabaseName("ix_binder_cards_scryfall_id");

                    b.HasIndex("BinderId", "CreatedAt")
                        .HasDatabaseName("ix_binder_cards_binder_id_created_at");

                    b.ToTable("binder_cards", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Catalogue.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.PrimitiveCollection<string[]>("BannedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("banned_formats");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collector_number");

                    b.PrimitiveCollection<string[]>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("color_identity");

                    b.PrimitiveCollection<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<bool>("Digital")
                        .HasColumnType("boolean")
                        .HasColumnName("digital");

                    b.Property<decimal?>("Eur")
                        .HasColumnType("numeric")
                        .HasColumnName("eur");

                    b.Property<decimal?>("EurFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("eur_foil");

                    b.PrimitiveCollection<string[]>("Finishes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("finishes");

                    b.Property<string>("FlavorText")
                        .HasColumnType("text")
                        .HasColumnName("flavor_text");

                    b.Property<bool>("FullArt")
                        .HasColumnType("boolean")
                        .HasColumnName("full_art");

                    b.Property<bool>("IsDefaultPrinting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_printing");

                    b.Property<bool>("IsMissingUpstream")
                        .HasColumnType("boolean")
                        .HasColumnName("is_missing_upstream");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.PrimitiveCollection<string[]>("LegalFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("legal_formats");

                    b.Property<string>("Loyalty")
                        .HasColumnType("text")
                        .HasColumnName("loyalty");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text")
                        .HasColumnName("mana_cost");

                    b.Property<decimal>("ManaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("mana_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<bool>("Oversized")
                        .HasColumnType("boolean")
                        .HasColumnName("oversized");

                    b.Property<string>("Power")
                        .HasColumnType("text")
                        .HasColumnName("power");

                    b.Property<bool>("Promo")
                        .HasColumnType("boolean")
                        .HasColumnName("promo");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<DateOnly>("ReleasedAt")
                        .HasColumnType("date")
                        .HasColumnName("released_at");

                    b.PrimitiveCollection<string[]>("RestrictedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("restricted_formats");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_code");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_type");

                    b.Property<decimal?>("Tix")
                        .HasColumnType("numeric")
                        .HasColumnName("tix");

                    b.Property<string>("Toughness")
                        .HasColumnType("text")
                        .HasColumnName("toughness");

                    b.Property<string>("TypeLine")
                        .HasColumnType("text")
                        .HasColumnName("type_line");

                    b.Property<decimal?>("Usd")
                        .HasColumnType("numeric")
                        .HasColumnName("usd");

                    b.Property<decimal?>("UsdEtched")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_etched");

                    b.Property<decimal?>("UsdFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_foil");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_cards_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OracleId")
                        .HasDatabaseName("ix_cards_oracle_id");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("ix_cards_set_code");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Catalogue.CatalogueSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BulkUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bulk_updated_at");

                    b.Property<int>("CardsRead")
                        .HasColumnType("integer")
                        .HasColumnName("cards_read");

                    b.Property<int>("DigitalSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("digital_skipped");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<int>("MissingUpstream")
                        .HasColumnType("integer")
                        .HasColumnName("missing_upstream");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_catalogue_sync_runs");

                    b.ToTable("catalogue_sync_runs", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Decks.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("format");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_decks");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_decks_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_decks_updated_at")
                        .HasFilter("is_public");

                    b.HasIndex("OwnerId", "UpdatedAt")
                        .HasDatabaseName("ix_decks_owner_id_updated_at");

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Prices.CardPriceSnapshot", b =>
                {
                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<decimal?>("Eur")
                        .HasColumnType("numeric")
                        .HasColumnName("eur");

                    b.Property<decimal?>("EurFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("eur_foil");

                    b.Property<decimal?>("Tix")
                        .HasColumnType("numeric")
                        .HasColumnName("tix");

                    b.Property<decimal?>("Usd")
                        .HasColumnType("numeric")
                        .HasColumnName("usd");

                    b.Property<decimal?>("UsdEtched")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_etched");

                    b.Property<decimal?>("UsdFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_foil");

                    b.HasKey("ScryfallId", "Provider", "Date")
                        .HasName("pk_card_price_snapshots");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_card_price_snapshots_date");

                    b.ToTable("card_price_snapshots", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Wishlist.WantedCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ScryfallId")
                        .HasColumnType("uuid")
                        .HasColumnName("scryfall_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wanted_cards");

                    b.HasIndex("ScryfallId")
                        .HasDatabaseName("ix_wanted_cards_scryfall_id");

                    b.HasIndex("OwnerId", "ScryfallId")
                        .IsUnique()
                        .HasDatabaseName("ix_wanted_cards_owner_id_scryfall_id");

                    b.ToTable("wanted_cards", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Binders.Binder", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_binders_users_owner_id");
                });

            modelBuilder.Entity("Deckino.Api.Binders.BinderCard", b =>
                {
                    b.HasOne("Deckino.Api.Binders.Binder", null)
                        .WithMany()
                        .HasForeignKey("BinderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_binder_cards_binders_binder_id");

                    b.HasOne("Deckino.Api.Catalogue.Card", null)
                        .WithMany()
                        .HasForeignKey("ScryfallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_binder_cards_cards_scryfall_id");
                });

            modelBuilder.Entity("Deckino.Api.Catalogue.Card", b =>
                {
                    b.OwnsOne("Deckino.Api.Catalogue.CardImages", "Images", b1 =>
                        {
                            b1.Property<Guid>("CardId");

                            b1.Property<string>("ArtCrop");

                            b1.Property<string>("Large")
                                .IsRequired();

                            b1.Property<string>("Normal")
                                .IsRequired();

                            b1.Property<string>("Small")
                                .IsRequired();

                            b1.HasKey("CardId")
                                .HasName("pk_cards");

                            b1.ToTable("cards");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CardId")
                                .HasConstraintName("fk_cards_cards_card_id");
                        });

                    b.OwnsMany("Deckino.Api.Catalogue.CardFace", "Faces", b1 =>
                        {
                            b1.Property<Guid>("CardId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FlavorText");

                            b1.Property<string>("Loyalty");

                            b1.Property<string>("ManaCost");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("OracleText");

                            b1.Property<string>("Power");

                            b1.Property<string>("Toughness");

                            b1.Property<string>("TypeLine");

                            b1.HasKey("CardId", "__synthesizedOrdinal")
                                .HasName("pk_cards");

                            b1.ToTable("cards");

                            b1
                                .ToJson("faces")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CardId")
                                .HasConstraintName("fk_cards_cards_card_id");

                            b1.OwnsOne("Deckino.Api.Catalogue.CardImages", "Images", b2 =>
                                {
                                    b2.Property<Guid>("CardFaceCardId");

                                    b2.Property<int>("CardFace__synthesizedOrdinal");

                                    b2.Property<string>("ArtCrop");

                                    b2.Property<string>("Large")
                                        .IsRequired();

                                    b2.Property<string>("Normal")
                                        .IsRequired();

                                    b2.Property<string>("Small")
                                        .IsRequired();

                                    b2.HasKey("CardFaceCardId", "CardFace__synthesizedOrdinal")
                                        .HasName("pk_cards");

                                    b2.ToTable("cards");

                                    b2.WithOwner()
                                        .HasForeignKey("CardFaceCardId", "CardFace__synthesizedOrdinal")
                                        .HasConstraintName("fk_cards_cards_card_face_card_id_card_face__synthesized_ordinal");
                                });

                            b1.Navigation("Images");
                        });

                    b.Navigation("Faces");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Deckino.Api.Decks.Deck", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_decks_users_owner_id");

                    b.OwnsOne("Deckino.Api.Decks.DeckCards", "Cards", b1 =>
                        {
                            b1.Property<Guid>("DeckId");

                            b1.HasKey("DeckId");

                            b1.ToTable("decks");

                            b1
                                .ToJson("cards")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("DeckId")
                                .HasConstraintName("fk_decks_decks_id");

                            b1.OwnsMany("Deckino.Api.Decks.DeckEntry", "Commander", b2 =>
                                {
                                    b2.Property<Guid>("DeckCardsDeckId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Finish")
                                        .IsRequired()
                                        .HasJsonPropertyName("finish");

                                    b2.Property<int>("Quantity")
                                        .HasJsonPropertyName("quantity");

                                    b2.Property<Guid>("ScryfallId")
                                        .HasJsonPropertyName("scryfallId");

                                    b2.HasKey("DeckCardsDeckId", "__synthesizedOrdinal")
                                        .HasName("pk_decks");

                                    b2.ToTable("decks");

                                    b2.HasJsonPropertyName("commander");

                                    b2.WithOwner()
                                        .HasForeignKey("DeckCardsDeckId")
                                        .HasConstraintName("fk_decks_decks_deck_cards_deck_id");
                                });

                            b1.OwnsMany("Deckino.Api.Decks.DeckEntry", "Mainboard", b2 =>
                                {
                                    b2.Property<Guid>("DeckCardsDeckId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Finish")
                                        .IsRequired()
                                        .HasJsonPropertyName("finish");

                                    b2.Property<int>("Quantity")
                                        .HasJsonPropertyName("quantity");

                                    b2.Property<Guid>("ScryfallId")
                                        .HasJsonPropertyName("scryfallId");

                                    b2.HasKey("DeckCardsDeckId", "__synthesizedOrdinal")
                                        .HasName("pk_decks");

                                    b2.ToTable("decks");

                                    b2.HasJsonPropertyName("mainboard");

                                    b2.WithOwner()
                                        .HasForeignKey("DeckCardsDeckId")
                                        .HasConstraintName("fk_decks_decks_deck_cards_deck_id");
                                });

                            b1.OwnsMany("Deckino.Api.Decks.DeckEntry", "Sideboard", b2 =>
                                {
                                    b2.Property<Guid>("DeckCardsDeckId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Finish")
                                        .IsRequired()
                                        .HasJsonPropertyName("finish");

                                    b2.Property<int>("Quantity")
                                        .HasJsonPropertyName("quantity");

                                    b2.Property<Guid>("ScryfallId")
                                        .HasJsonPropertyName("scryfallId");

                                    b2.HasKey("DeckCardsDeckId", "__synthesizedOrdinal")
                                        .HasName("pk_decks");

                                    b2.ToTable("decks");

                                    b2.HasJsonPropertyName("sideboard");

                                    b2.WithOwner()
                                        .HasForeignKey("DeckCardsDeckId")
                                        .HasConstraintName("fk_decks_decks_deck_cards_deck_id");
                                });

                            b1.Navigation("Commander");

                            b1.Navigation("Mainboard");

                            b1.Navigation("Sideboard");
                        });

                    b.Navigation("Cards")
                        .IsRequired();
                });

            modelBuilder.Entity("Deckino.Api.Wishlist.WantedCard", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wanted_cards_users_owner_id");

                    b.HasOne("Deckino.Api.Catalogue.Card", null)
                        .WithMany()
                        .HasForeignKey("ScryfallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wanted_cards_cards_scryfall_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Deckino.Api.Accounts.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
