// <auto-generated />
using System;
using Deckino.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deckino.Api.Migrations
{
    [DbContext(typeof(DeckinoDbContext))]
    [Migration("20261006145913_CardCatalogue")]
    partial class CardCatalogue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deckino.Api.Catalogue.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Artist")
                        .HasColumnType("text")
                        .HasColumnName("artist");

                    b.PrimitiveCollection<string[]>("BannedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("banned_formats");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("collector_number");

                    b.PrimitiveCollection<string[]>("ColorIdentity")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("color_identity");

                    b.PrimitiveCollection<string[]>("Colors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("colors");

                    b.Property<bool>("Digital")
                        .HasColumnType("boolean")
                        .HasColumnName("digital");

                    b.Property<decimal?>("Eur")
                        .HasColumnType("numeric")
                        .HasColumnName("eur");

                    b.Property<decimal?>("EurFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("eur_foil");

                    b.PrimitiveCollection<string[]>("Finishes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("finishes");

                    b.Property<string>("FlavorText")
                        .HasColumnType("text")
                        .HasColumnName("flavor_text");

                    b.Property<bool>("FullArt")
                        .HasColumnType("boolean")
                        .HasColumnName("full_art");

                    b.Property<bool>("IsDefaultPrinting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_printing");

                    b.Property<bool>("IsMissingUpstream")
                        .HasColumnType("boolean")
                        .HasColumnName("is_missing_upstream");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lang");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.PrimitiveCollection<string[]>("LegalFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("legal_formats");

                    b.Property<string>("Loyalty")
                        .HasColumnType("text")
                        .HasColumnName("loyalty");

                    b.Property<string>("ManaCost")
                        .HasColumnType("text")
                        .HasColumnName("mana_cost");

                    b.Property<decimal>("ManaValue")
                        .HasColumnType("numeric")
                        .HasColumnName("mana_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OracleId")
                        .HasColumnType("uuid")
                        .HasColumnName("oracle_id");

                    b.Property<string>("OracleText")
                        .HasColumnType("text")
                        .HasColumnName("oracle_text");

                    b.Property<bool>("Oversized")
                        .HasColumnType("boolean")
                        .HasColumnName("oversized");

                    b.Property<string>("Power")
                        .HasColumnType("text")
                        .HasColumnName("power");

                    b.Property<bool>("Promo")
                        .HasColumnType("boolean")
                        .HasColumnName("promo");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<DateOnly>("ReleasedAt")
                        .HasColumnType("date")
                        .HasColumnName("released_at");

                    b.PrimitiveCollection<string[]>("RestrictedFormats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("restricted_formats");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_code");

                    b.Property<string>("SetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_name");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("set_type");

                    b.Property<decimal?>("Tix")
                        .HasColumnType("numeric")
                        .HasColumnName("tix");

                    b.Property<string>("Toughness")
                        .HasColumnType("text")
                        .HasColumnName("toughness");

                    b.Property<string>("TypeLine")
                        .HasColumnType("text")
                        .HasColumnName("type_line");

                    b.Property<decimal?>("Usd")
                        .HasColumnType("numeric")
                        .HasColumnName("usd");

                    b.Property<decimal?>("UsdEtched")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_etched");

                    b.Property<decimal?>("UsdFoil")
                        .HasColumnType("numeric")
                        .HasColumnName("usd_foil");

                    b.HasKey("Id")
                        .HasName("pk_cards");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_cards_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OracleId")
                        .HasDatabaseName("ix_cards_oracle_id");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("ix_cards_set_code");

                    b.ToTable("cards", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Catalogue.CatalogueSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("BulkUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bulk_updated_at");

                    b.Property<int>("CardsRead")
                        .HasColumnType("integer")
                        .HasColumnName("cards_read");

                    b.Property<int>("DigitalSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("digital_skipped");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Inserted")
                        .HasColumnType("integer")
                        .HasColumnName("inserted");

                    b.Property<int>("MissingUpstream")
                        .HasColumnType("integer")
                        .HasColumnName("missing_upstream");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Updated")
                        .HasColumnType("integer")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_catalogue_sync_runs");

                    b.ToTable("catalogue_sync_runs", (string)null);
                });

            modelBuilder.Entity("Deckino.Api.Catalogue.Card", b =>
                {
                    b.OwnsOne("Deckino.Api.Catalogue.CardImages", "Images", b1 =>
                        {
                            b1.Property<Guid>("CardId");

                            b1.Property<string>("Large")
                                .IsRequired();

                            b1.Property<string>("Normal")
                                .IsRequired();

                            b1.Property<string>("Small")
                                .IsRequired();

                            b1.HasKey("CardId")
                                .HasName("pk_cards");

                            b1.ToTable("cards");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CardId")
                                .HasConstraintName("fk_cards_cards_card_id");
                        });

                    b.OwnsMany("Deckino.Api.Catalogue.CardFace", "Faces", b1 =>
                        {
                            b1.Property<Guid>("CardId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("FlavorText");

                            b1.Property<string>("Loyalty");

                            b1.Property<string>("ManaCost");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("OracleText");

                            b1.Property<string>("Power");

                            b1.Property<string>("Toughness");

                            b1.Property<string>("TypeLine");

                            b1.HasKey("CardId", "__synthesizedOrdinal")
                                .HasName("pk_cards");

                            b1.ToTable("cards");

                            b1
                                .ToJson("faces")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CardId")
                                .HasConstraintName("fk_cards_cards_card_id");

                            b1.OwnsOne("Deckino.Api.Catalogue.CardImages", "Images", b2 =>
                                {
                                    b2.Property<Guid>("CardFaceCardId");

                                    b2.Property<int>("CardFace__synthesizedOrdinal");

                                    b2.Property<string>("Large")
                                        .IsRequired();

                                    b2.Property<string>("Normal")
                                        .IsRequired();

                                    b2.Property<string>("Small")
                                        .IsRequired();

                                    b2.HasKey("CardFaceCardId", "CardFace__synthesizedOrdinal")
                                        .HasName("pk_cards");

                                    b2.ToTable("cards");

                                    b2.WithOwner()
                                        .HasForeignKey("CardFaceCardId", "CardFace__synthesizedOrdinal")
                                        .HasConstraintName("fk_cards_cards_card_face_card_id_card_face__synthesized_ordinal");
                                });

                            b1.Navigation("Images");
                        });

                    b.Navigation("Faces");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
